// https://www.codechef.com/START32D/problems/VOLCONTROL

// Volume Control

#include <iostream>
using namespace std;

void solve()
{
    int a, b;
    cin >> a >> b;

    int ans = abs(a - b);
    cout << ans << "\n";
}

int main(void)
{
    // KNOCKCAT

    int t;
    cin >> t;
    while (t--)
    {
        solve();
    }
    return 0;
}

// Solution Link

// https://www.codechef.com/viewsolution/61675490
